[package]
name = "bevy-test"
version = "0.1.0"
authors = ["Pravin Kumar <pravinshanmugam1995@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.2" 
bevy_window = "0.1.0"